<meta charset="UTF-8">
<meta name="author" content="Tony Yip(4D 2013)">
<script src="http://elearn.pyc.edu.hk/console/SilverSnake/UI/js.php?UI=bootstrap"></script>
<link href="http://<?= $_SERVER['HTTP_HOST']?>/library/img/pyc.gif" rel="icon" type="image/gif" />
<link href="http://<?= $_SERVER["HTTP_HOST"]?>/console/SilverSnake/css/?system=bootstrap" rel="stylesheet" type="text/css" />
<link href="http://<?= $_SERVER["HTTP_HOST"]?>/library/css/core.css" rel="stylesheet" type="text/css" />
<!--[if lt IE 11]>
<script src="http://<?= $_SERVER['HTTP_HOST']?>/pydio/data/personal/console/cdn/shiv/html5shiv/html5shiv.js"></script>
<script src="http://<?= $_SERVER['HTTP_HOST']?>/pydio/data/personal/console/cdn/shiv/respond/respond.min.js"></script>
<![endif]-->
<title>沙田培英中學圖書館</title>
