<meta charset="UTF-8">
<meta name="author" content="Tony Yip(4D 2013)">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<script src="http://elearn.pyc.edu.hk/console/SilverSnake/UI/js.php?UI=bootstrap"></script>
<link href="http://<?= $_SERVER['HTTP_HOST']?>/library/img/pyc.gif" rel="icon" type="image/gif" />
<link href="http://<?= $_SERVER["HTTP_HOST"]?>/console/SilverSnake/css/?system=bootstrap" rel="stylesheet" type="text/css" />
<link href="http://<?= $_SERVER["HTTP_HOST"]?>/library/css/common.css" rel="stylesheet" type="text/css" />
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55062795-1', 'auto');
  ga('send', 'pageview');

</script>
<!--[if lt IE 11]>
<script src="http://<?= $_SERVER['HTTP_HOST']?>/console/cdn/shiv/html5shiv/html5shiv.js"></script>
<script src="http://<?= $_SERVER['HTTP_HOST']?>/console/cdn/shiv/respond/respond.min.js"></script>
<![endif]-->
<title>沙田培英中學圖書館</title>
