<table align="center" border="1" cellpadding="0" cellspacing="0" style="width:597px">
	<tbody>
		<tr>
			<td colspan="11" rowspan="2" style="height:44px; text-align:center; width:597px"><strong><u>沙田培英中學圖書館管理員當值時間表</u></strong></td>
		</tr>
		<tr>
		</tr>
		<tr>
			<td colspan="11" style="height:22px">　</td>
		</tr>
		<tr>
			<td style="height:22px">　</td>
			<td><strong>星期一</strong></td>
			<td><strong>　</strong></td>
			<td><strong>星期二</strong></td>
			<td><strong>　</strong></td>
			<td><strong>星期三</strong></td>
			<td><strong>　</strong></td>
			<td><strong>星期四</strong></td>
			<td><strong>　</strong></td>
			<td><strong>星期五</strong></td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px"><strong>主席</strong></td>
			<td>5D方樂天</td>
			<td>　</td>
			<td>5A陳瑋霆</td>
			<td>　</td>
			<td>輪更</td>
			<td>　</td>
			<td>5A林諾庭</td>
			<td>　</td>
			<td>5A黎家敏</td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px"><strong>組長</strong></td>
			<td style="width:77px">5D陳蔚林</td>
			<td style="width:27px">　</td>
			<td style="width:77px">5E丘皓婷&nbsp;</td>
			<td style="width:28px">　</td>
			<td style="width:77px">4F黃明新</td>
			<td style="width:28px">　</td>
			<td style="width:77px">5A李海量</td>
			<td style="width:28px">　</td>
			<td style="width:77px">5E陳家婷</td>
			<td style="width:28px">　</td>
		</tr>
		<tr>
			<td colspan="11" style="height:22px">　</td>
		</tr>
		<tr>
			<td style="height:22px"><strong>小息</strong></td>
			<td>2B蔡愷恩</td>
			<td>　</td>
			<td>2A林諾恩</td>
			<td>　</td>
			<td>1C陳凱愉</td>
			<td>　</td>
			<td>1D張佳美</td>
			<td>　</td>
			<td>2C李卓瑤</td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px">　</td>
			<td>2B鄺澔儀</td>
			<td>　</td>
			<td>2A鍾淑瑩</td>
			<td>　</td>
			<td>1D方小敏</td>
			<td>　</td>
			<td>2C姚靖彤</td>
			<td>　</td>
			<td>2C林芷晴</td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px">　</td>
			<td>2D陳卓妍</td>
			<td>　</td>
			<td>4D葉浩匡</td>
			<td>　</td>
			<td>1D郭千悅</td>
			<td>　</td>
			<td>4D葉浩匡</td>
			<td>　</td>
			<td>4D葉浩匡</td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px">　</td>
			<td>2D陳金釗</td>
			<td>　</td>
			<td>4F林蔚盈</td>
			<td>　</td>
			<td>4D葉浩匡</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px">　</td>
			<td>2D蘇津錡</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>5E甄俊彥</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px">　</td>
			<td>4D葉浩匡</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>&nbsp;</td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px">　</td>
			<td>4D李卓盈</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px">　</td>
			<td>4E賴國英</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px">　</td>
			<td>4F余敏婷</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
		</tr>
		<tr>
			<td colspan="11" style="height:22px">　</td>
		</tr>
		<tr>
			<td style="height:22px"><strong>午膳</strong></td>
			<td>2B蔡愷恩</td>
			<td>　</td>
			<td>2A林諾恩</td>
			<td>　</td>
			<td>1C陳凱愉</td>
			<td>　</td>
			<td>1D張佳美</td>
			<td>　</td>
			<td>2C李卓瑤</td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px">　</td>
			<td>2B鄺澔儀</td>
			<td>　</td>
			<td>2A鍾淑瑩</td>
			<td>　</td>
			<td>1D方小敏</td>
			<td>　</td>
			<td>2C姚靖彤</td>
			<td>　</td>
			<td>2C林芷晴</td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px">　</td>
			<td>3D吳倩雯</td>
			<td>　</td>
			<td>3C唐樂謙</td>
			<td>　</td>
			<td>1D郭千悅</td>
			<td>　</td>
			<td>4D葉浩匡</td>
			<td>　</td>
			<td>3D吳倩雯</td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px">　</td>
			<td>4D葉浩匡</td>
			<td>　</td>
			<td>4D葉浩匡</td>
			<td>　</td>
			<td>3D吳倩雯</td>
			<td>　</td>
			<td>2D陳卓妍</td>
			<td>　</td>
			<td>4D葉浩匡</td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px">　</td>
			<td>4D李卓盈</td>
			<td>　</td>
			<td>4F林蔚盈</td>
			<td>　</td>
			<td>4D葉浩匡</td>
			<td>　</td>
			<td>2D陳金釗</td>
			<td>　</td>
			<td>2D陳卓妍</td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px">　</td>
			<td>4E賴國英</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>5E甄俊彥</td>
			<td>　</td>
			<td>2D蘇津錡</td>
			<td>　</td>
			<td>2D陳金釗</td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px">　</td>
			<td>4F余敏婷</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
			<td>2D蘇津錡</td>
			<td>　</td>
		</tr>
		<tr>
			<td colspan="11" style="height:22px">　</td>
		</tr>
		<tr>
			<td style="height:22px"><strong>放學</strong></td>
			<td>3B劉君婷</td>
			<td>　</td>
			<td>2A郭晞潼</td>
			<td>　</td>
			<td>1A陳曉欣</td>
			<td>　</td>
			<td>3A周頌恩</td>
			<td>　</td>
			<td>2A區嘉賢</td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px">　</td>
			<td>3D譚希琳</td>
			<td>　</td>
			<td>3A顏穎雪</td>
			<td>　</td>
			<td>1A趙心妍</td>
			<td>　</td>
			<td>3D凌卓怡</td>
			<td>　</td>
			<td>3A譚咏詩</td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px">　</td>
			<td>　</td>
			<td>　</td>
			<td>3C范凱淇</td>
			<td>　</td>
			<td>1A李樂儀</td>
			<td>　</td>
			<td>4D李進義</td>
			<td>　</td>
			<td>3A雷逸盈</td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px">　</td>
			<td>　</td>
			<td>　</td>
			<td>3D凌卓怡</td>
			<td>　</td>
			<td>3C許曉璁</td>
			<td>　</td>
			<td>4E張陽光</td>
			<td>　</td>
			<td>3D梁曉霖</td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px">　</td>
			<td>　</td>
			<td>　</td>
			<td>3D潘柳婷</td>
			<td>　</td>
			<td>3C楊逸軒</td>
			<td>　</td>
			<td>4F何雋文</td>
			<td>　</td>
			<td>3D鍾芷珊</td>
			<td>　</td>
		</tr>
		<tr>
			<td style="height:22px">　</td>
			<td>　</td>
			<td>　</td>
			<td>3C唐樂謙</td>
			<td>　</td>
			<td>3D譚希琳</td>
			<td>　</td>
			<td>5B梁浚洛</td>
			<td>　</td>
			<td>　</td>
			<td>　</td>
		</tr>
	</tbody>
</table>
